name: Sync main branch
on:
  push:
    branches:
      - 'main'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Merge main -> versioned
        uses: devmasx/merge-branch@854d3ac71ed1e9deb668e0074781b81fdd6e771f # v1.4.0
        with:
          type: now
          from_branch: main
          target_branch: versioned
          github_token: ${{ github.token }}
